### ISSUE TITLE
Show toast on screenshot on a secure app

### ISSUE THREAD

**Issue by shariful2011** [neckaros/secure_application#10]
How can I show a toast when the user wants to take a screenshot of my app which is under your very good package? I used the example for testing purposes. Your early response will be highly appreciated.

**Comment by justkawal** [comment]
@shariful2011 
You can easily show a snack-bar, when the user tries to take screenshot.

https://flutter.dev/docs/cookbook/design/snackbars

**Comment by shariful2011** [comment]
but what is the callback when the user tries to take a screenshot? @justkawal.

**Comment by neckaros** [comment]
@shariful2011 sorry i missed your question. You are on Android?

**Comment by shariful2011** [comment]
@neckaros yes. Also I found out that on some phones it shows a snackbar.

**Comment by neckaros** [comment]
this is not currently implemend by this package.
I found this article it might help: https://proandroiddev.com/detect-screenshots-in-android-7bc4343ddce1
I will add it to backlog but no garantee
