### ISSUE TITLE
nativeRemoveDelay is null and that makes the app crash

### ISSUE THREAD

**Issue by Rodsevich** [neckaros/secure_application#16]
I have only copied the code from the readme and the app is crashing when coming back from background because of nativeRemoveDelay isn't required nor by default initialized. This is the code that fails because of the !:
https://github.com/neckaros/secure_application/blob/b87a7aac57e12bb62c902582ea7ab7b5e4dea30f/lib/secure_application.dart#L159
I declared nativeRemoveDelay and the crash was gone.

**Comment by neckaros** [comment]
Thank you very much i will fix it ASAP!

**Comment by neckaros** [comment]
Should be fixed in 3.7.3 avaialble on Pub.dev

Please reopen if you still have the issue
