### ISSUE TITLE
Web implementation

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [neckaros/secure_application#27]
Hey there
I was searching for something that could completely prevent screenshots of my app and found your package
So what I'm asking is this, does it show blur on web when the the browser goes to background?
And if not, can this be done or anything equivalent to locking the app content when it goes to background in web or when the tab is inactive?
Also is there such a thing to prevent screenshots on web when the browsed in a mobile?

**Comment by neckaros** [comment]
The blur screen will trigger if the page is no longer on screen and you come back to it. Not sure it will meet your requirements. You can clone this repo locally and run the exemple app in chrome to test
