### ISSUE TITLE
Support Up-to-date dependencies

### ISSUE THREAD

**Issue by davidchristian1** [neckaros/secure_application#32]
Currently, this package depends on rxdart ^0.26.0. Can you please update the rxdart version (to rxdart ^0.27.3)? I want to use this package but I cannot install it because of this version issue :(  Thank you.

**Comment by m-spiridon** [comment]
I would also appreciate this update. Thank you!

**Comment by mohanadshaban** [comment]
Yes Please +++

**Comment by JThorvid** [comment]
I would appreciate this as well, since this causes problems for me with the assets_audio_player.
There is even a fork that uses the newer rxdart (https://github.com/neckaros/secure_application/compare/master...ariefwijaya:master). I have not tried it though.

**Comment by neckaros** [comment]
thanks for the info. I merged a pull request from the repo you provided @JThorvid
