### ISSUE TITLE
Presumably wrong documentation

### ISSUE THREAD

**Issue by JThorvid** [neckaros/secure_application#36]
On https://pub.dev/documentation/secure_application/latest/secure_application/SecureApplication-class.html is says:
[onLogout](https://pub.dev/documentation/secure_application/latest/secure_application/SecureApplication/onLogout.html) → [VoidCallback](https://api.dart.dev/stable/2.17.1/dart-ui/VoidCallback.html)?
    will be called if authentication succeed
    final

I assume this function gets called when the user logs out, not when the authentication succeeded.

**Comment by neckaros** [comment]
Thanks for the heads up!
