### ISSUE TITLE
How to secure all the pages of the app?

### ISSUE THREAD

**Issue by 0Vipin0** [neckaros/secure_application#4]
I am trying to develop an app that has multiple screens. Whenever the user goes to the background and then comes to foreground, then I should be prompted to authenticate before going to other screen. I have tried many things but unable to understand how to implement it. 
Can you help me on how to do that  @neckaros ?

**Comment by neckaros** [comment]
Hello

Did you try to have it as described in the read me placement section?
https://github.com/neckaros/secure_application#placement

**Comment by 0Vipin0** [comment]
Yes, I read the complete Readme and used it as specified in the Readme. Sorry, If i wasn't complete give details of my problem.

What I am trying to accomplish is that 
-  Anytime the app goes in the background, then it comes to foreground, I should be prompted to unlock the screen before entering in the app and this should be applied to any screen that the user is on.

What my issue is
- Whenever I once unlocked the application using the lockedBuilder and navigated to the other screen, then the app is opened for every other screen, even though I have applied the secure gate just below material app.
- The app doesn't get secured in the recent app option, even though there is no error in the logs

What I have tried
- I have tried the AppLifeCycleState to manage when the app goes to the background, then comes to foreground. But since there is no context in the didAppLifeCycleStateChanged, so it gives me context not found error.

- I have to dynamically build the screen using SecureApplicationProvider, But It doesn't work too.

I hope i am able to give the question detail clearly @neckaros.

**Comment by neckaros** [comment]
To sum up even after unlock and moving to another screen you still want the app to be protected . That should be how it works (and is how it works in my own app)

How do you unlock when the user get back to the app? You should use unlock() and not open()
Are you able to reproduce in a minimal app?

**Comment by 0Vipin0** [comment]
Yeah that sums up. I tried the unlock not open. I will implement a minimal app. Then update here if the issue is resolved or not.

**Comment by neckaros** [comment]
Hello do you still have the issue or can i close it?

**Comment by 0Vipin0** [comment]
Sorry to for not replying earlier. I just implemented the security natively in the android and ios. So I haven't used the library there. You can close the issue. Thank for your reply.
