### ISSUE TITLE
A package version with rxdart ^0.27.x support has not yet been released

### ISSUE THREAD

**Issue by SimoneBressan** [neckaros/secure_application#42]
Could you release a new version?
I see the pubspec has already been updated to support the latest version of rxdart.
It would be great to have a release!

**Comment by wszeborowskimateusz** [comment]
Any update here?

**Comment by GabM3** [comment]
can you release please?

**Comment by rambozzang** [comment]
secure_application: 
    git:
      url: https://github.com/neckaros/secure_application.git

**Comment by ManuelRauber** [comment]
@neckaros Hi! Could you please check this? Apps using secure_application will have issues in the future when other packages depend on a newer rxdart version.

It would be great, if you can release a new version with a current rxdart.

Thanks! :)

**Comment by neckaros** [comment]
Sorry i have not been able to work on dart for a while and won't trust myself with it right now. Anyone willing to do a pull request?

**Comment by neckaros** [comment]
I have pushed V4.0.0 of the package. Please report if you see any issue
