### ISSUE TITLE
Hello, can you set it to be blurred in the background? It's black now.

### ISSUE THREAD

**Issue by kmarryme** [neckaros/secure_application#8]
![Screenshot_1599033580](https://user-images.githubusercontent.com/43201456/91955243-77f7ce80-ed35-11ea-8e68-041b0b15215d.png)

**Comment by neckaros** [comment]
Sorry that’s how Android manage secured applications :
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE

**Comment by neckaros** [comment]
limitation of android in the app swithcer

**Comment by CatEatFishs** [comment]
IOS how to set background？
